CREATE DATABASE orangedb;
CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  perfilPhoto BLOB,
  country VARCHAR(255)
);
CREATE TABLE project (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  tags VARCHAR(255),
  link VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  coverphoto BLOB,
  fk_iduser INT NOT NULL,
  FOREIGN KEY (fk_iduser) REFERENCES User (id)
);